### ISSUE TITLE
Build failures on OpenSSL

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydro#1504]
Build targets: 
- `Build CLI / linux (x86_64-unknown-linux-gnu) (push)`

Gives:
```
running cd "/home/runner/work/hydroflow/hydroflow/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-98ec79c8ab394428/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" "make" "build_libs"
  /usr/bin/perl util/mkinstallvars.pl PREFIX=. BINDIR=apps APPLINKDIR=ms LIBDIR= INCLUDEDIR=include "INCLUDEDIR=./include" ENGINESDIR=engines MODULESDIR=providers "VERSION=3.3.2" "LDLIBS=-ldl -pthread " > builddata.pm

  --- stderr
  "pairs" is not exported by the List::Util module
  Can't continue after import errors at util/mkinstallvars.pl line 14.
  BEGIN failed--compilation aborted at util/mkinstallvars.pl line 14.
  make: *** [builddata.pm] Error 255
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.3.2+3.3.2/src/lib.rs:633:9:



  Error building OpenSSL:
      Command: cd "/home/runner/work/hydroflow/hydroflow/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-98ec79c8ab394428/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" "make" "build_libs"
      Exit status: exit status: 2


      
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO "cargo" "rustc" "--features" "pyo3/extension-module" "--target" "x86_64-unknown-linux-gnu" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/runner/work/hydroflow/hydroflow/hydro_deploy/hydro_cli/Cargo.toml" "--release" "--lib"`
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by shadaj** [comment]
https://github.com/openssl/openssl/issues/25366

**Comment by MingweiSamuel** [comment]
Fixed at some point
